### ISSUE TITLE
Unable to regenerate nsall.h

### ISSUE THREAD

**Issue by dpage** [jonmmorgan/wxwebconnect#4]
Hi,

How are you regenerating nsall.h? When I attempt to do so using xpidl from the 1.9.2 SDK, the resulting header file is unusable - for example, it adds NS_SCRIPTABLE decoration which isn't in the original file, and causes compilation errors such as:

nsall.h(33) : error C2470: 'nsISupports' : looks like a function definition, but there is no parameter list; skipping apparent body

I'm attempting to add support for binary data in the custom protocol handler, for which (if I've understood the API docs correctly) I need an interface for nsIOutputStream.

Thanks.

**Comment by jonmmorgan** [comment]
That is a very good question, which I had forgotten about.  The current version of wxWebConnect relies on the xpidl from the 1.8.0 SDK.  While this works with IDL files from 1.9.2 (and hopefully from later versions as well), it is rather hard to get hold of (from memory, Mozilla don't even distribute a source tarball for it any more).  Early on I spent a couple of hours trying to make it work with 1.9.2 XULRunner, but when I realised it would take a lot of work and make it very difficult to merge changes from upstream I gave up.  I have been using a binary xpidl for Windows which was statically linked which I found somewhere (possibly from https://developer.mozilla.org/User:Andywang/xpidl?)  I'd love a more up to date solution, but I don't think it very likely for quite a while.

**Comment by jonmmorgan** [comment]
Just for reference, I commented about these things back at the end of May at http://www.kirix.com/forums/viewtopic.php?f=25&t=822.  That forum post might also give more details about some of my concerns with the XULRunner 1.8.x oriented code.

**Comment by dpage** [comment]
Cool, thanks. I did wonder if it was an older rev of xpidl, but couldn't find one. I'll give that link a whirl.
